<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
        <PackageReference Include="Avalonia" Version="11.3.7" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.2"/>
        <PackageReference Include="FlashCap" Version="1.11.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
        <PackageReference Include="Microsoft.Toolkit.HighPerformance" Version="7.1.2" />
        <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
        <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
        <PackageReference Include="ReactiveUI" Version="22.0.1" />
        <PackageReference Include="System.Drawing.Common" Version="4.5.0" />
    </ItemGroup>


    <ItemGroup>
      <Compile Update="CollapsiblePanel.axaml.cs">
        <DependentUpon>CollapsiblePanel.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\Twinkly.Net\Twinkly.Net.csproj" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\Twinkly.Net\Twinkly.Net.csproj" />
    </ItemGroup>
</Project>
